package com.patrick.fintech.loan_backend.service;
import com.patrick.fintech.loan_backend.model.*; import com.patrick.fintech.loan_backend.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.io.*; import java.math.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor
public class BankReconciliationService{
 private final BankStatementLineRepository statementRepo; private final BankAccountRepository bankRepo; private final JournalLineRepository lineRepo;
 @Transactional public int importCsv(Organization org,Long bankAccountId,InputStream input,String actor)throws IOException{
  BankAccount account=bankRepo.findByIdAndOrganization_Id(bankAccountId,org.getId()).orElseThrow(()->new IllegalArgumentException("Bank account not found")); if(account.getGlAccount()==null||account.getGlAccount().getId()==null)throw new IllegalStateException("Bank account has no GL account"); int count=0; try(BufferedReader r=new BufferedReader(new InputStreamReader(input,StandardCharsets.UTF_8))){String h=r.readLine(); if(h==null)throw new IllegalArgumentException("CSV is empty"); Map<String,Integer> m=headers(h); require(m,"transaction_date");require(m,"amount"); String row; while((row=r.readLine())!=null){if(row.isBlank())continue;List<String> c=parse(row);LocalDate date=LocalDate.parse(val(c,m,"transaction_date"));BigDecimal amount=new BigDecimal(val(c,m,"amount")).setScale(2,RoundingMode.HALF_UP);String ext=opt(c,m,"external_id"); if(ext!=null&&statementRepo.findByOrganization_IdAndBankAccount_IdAndExternalId(org.getId(),bankAccountId,ext).isPresent())continue; statementRepo.save(BankStatementLine.builder().organization(org).bankAccount(account).transactionDate(date).valueDate(parseDate(opt(c,m,"value_date"))).reference(opt(c,m,"reference")).description(opt(c,m,"description")).amount(amount).currency(Optional.ofNullable(opt(c,m,"currency")).orElse("RWF")).externalId(ext).matchedBy(actor).build());count++;}} return count;
 }
 @Transactional public ReconciliationResult reconcile(Organization org,Long bankAccountId,LocalDate from,LocalDate to,String actor){BankAccount account=bankRepo.findByIdAndOrganization_Id(bankAccountId,org.getId()).orElseThrow(()->new IllegalArgumentException("Bank account not found"));if(account.getGlAccount()==null||account.getGlAccount().getId()==null)throw new IllegalStateException("Bank account has no GL account");List<BankStatementLine> lines=statementRepo.findByOrganization_IdAndBankAccount_IdAndTransactionDateBetweenOrderByTransactionDateAscIdAsc(org.getId(),bankAccountId,from,to);List<JournalLine> ledger=lineRepo.findLedgerForAccountAndOrganization(account.getGlAccount().getId(),org.getId());List<Map<String,Object>> unmatched=new ArrayList<>();int matched=0;Set<Long> used=new HashSet<>();for(BankStatementLine s:lines){if("MATCHED".equals(s.getReconciliationStatus())){matched++;continue;}JournalLine best=null;for(JournalLine l:ledger){if(l.getJournalEntry()==null||l.getJournalEntry().getEntryDate().isBefore(from)||l.getJournalEntry().getEntryDate().isAfter(to)||used.contains(l.getId()))continue;BigDecimal net=l.getDebitDecimal().subtract(l.getCreditDecimal());if(net.compareTo(s.getAmount())!=0)continue;String ref=l.getJournalEntry().getReference();String sr=s.getReference();boolean refOk=sr!=null&&ref!=null&&(!sr.isBlank()&&ref.toLowerCase(Locale.ROOT).contains(sr.toLowerCase(Locale.ROOT)));if(refOk||s.getTransactionDate().equals(l.getJournalEntry().getEntryDate())){best=l;break;}}if(best!=null){s.setReconciliationStatus("MATCHED");s.setMatchedJournalEntryId(best.getJournalEntry().getId());s.setMatchedAt(LocalDateTime.now());s.setMatchedBy(actor);statementRepo.save(s);used.add(best.getId());matched++;}else{unmatched.add(Map.of("statementLineId",s.getId(),"date",s.getTransactionDate().toString(),"amount",s.getAmount(),"reference",Optional.ofNullable(s.getReference()).orElse("")));}}
 BigDecimal statementTotal=lines.stream().map(BankStatementLine::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal ledgerTotal=ledger.stream().filter(l->l.getJournalEntry()!=null&&!l.getJournalEntry().getEntryDate().isBefore(from)&&!l.getJournalEntry().getEntryDate().isAfter(to)).map(l->l.getDebitDecimal().subtract(l.getCreditDecimal())).reduce(BigDecimal.ZERO,BigDecimal::add);return new ReconciliationResult(account.getId(),from,to,lines.size(),matched,lines.size()-matched,statementTotal.setScale(2,RoundingMode.HALF_UP),ledgerTotal.setScale(2,RoundingMode.HALF_UP),statementTotal.subtract(ledgerTotal).setScale(2,RoundingMode.HALF_UP),unmatched,sha256(org.getId()+"|"+bankAccountId+"|"+from+"|"+to+"|"+statementTotal+"|"+ledgerTotal));}
 public record ReconciliationResult(Long bankAccountId,LocalDate from,LocalDate to,int statementLines,int matched,int unmatched,BigDecimal statementNet,BigDecimal ledgerNet,BigDecimal difference,List<Map<String,Object>> unmatchedItems,String reportHash){}
 private Map<String,Integer> headers(String h){Map<String,Integer> m=new HashMap<>();List<String> x=parse(h);for(int i=0;i<x.size();i++)m.put(x.get(i).trim().toLowerCase(Locale.ROOT),i);return m;} private void require(Map<String,Integer>m,String k){if(!m.containsKey(k))throw new IllegalArgumentException("Missing CSV column: "+k);} private String val(List<String>c,Map<String,Integer>m,String k){int i=m.get(k);if(i>=c.size())throw new IllegalArgumentException("Missing value for "+k);return c.get(i).trim();} private String opt(List<String>c,Map<String,Integer>m,String k){return !m.containsKey(k)||m.get(k)>=c.size()||c.get(m.get(k)).isBlank()?null:c.get(m.get(k)).trim();} private LocalDate parseDate(String s){return s==null?null:LocalDate.parse(s);} private List<String> parse(String s){List<String>r=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(char c:s.toCharArray()){if(c=='"'){q=!q;continue;}if(c==','&&!q){r.add(b.toString());b.setLength(0);}else b.append(c);}r.add(b.toString());return r;} private String sha256(String s){try{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder x=new StringBuilder();for(byte v:b)x.append(String.format("%02x",v));return x.toString();}catch(Exception e){throw new IllegalStateException(e);}}
}
