"use client";
import Link from "next/link";
const faqs=[
 ["What is a personal loan?","A personal loan is financing repaid over an agreed period under the terms of a loan agreement. Eligibility, fees, interest and repayment schedules depend on the approved product."],
 ["How is my monthly payment calculated?","A standard fixed-payment loan uses the principal, periodic interest rate and number of payments. Noble products may also have product-specific fees or repayment rules, so the final agreement controls."],
 ["Does the calculator guarantee approval?","No. Calculator results are estimates for planning. Approval, amount, pricing and final terms are subject to assessment and verification."],
 ["What information may I need to apply?","Depending on the product, you may be asked for identity, contact, income, employment, business or supporting financial information."],
 ["Can I track my application?","Yes. Use the Track application page with the reference information provided during your application."],
 ["What if I need help?","Our team can help with application questions, product information and existing application support."],
];
export default function FAQPage(){return <main className="bg-slate-50"><div className="mx-auto max-w-5xl px-5 py-14 sm:px-8 sm:py-20"><p className="text-xs font-black uppercase tracking-[.18em] text-[#C9A227]">Help & FAQs</p><h1 className="mt-3 text-4xl font-black tracking-[-.04em] text-slate-950 sm:text-5xl">Answers before you apply.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-500">Straightforward information about Noble loans, calculations and the application journey.</p><div className="mt-10 space-y-3">{faqs.map(([q,a])=><details key={q} className="group rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer list-none pr-8 text-sm font-black text-slate-950">{q}<span className="float-right text-slate-400">+</span></summary><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-500">{a}</p></details>)}</div><div className="mt-10 rounded-3xl bg-slate-950 p-7 text-white"><h2 className="text-2xl font-black">Ready to explore your options?</h2><p className="mt-2 text-sm text-white/55">Start an application or calculate an indicative payment first.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/apply" className="rounded-xl bg-[#C9A227] px-5 py-3 text-sm font-black text-slate-950">Start application</Link><Link href="/loan-calculator" className="rounded-xl border border-white/15 px-5 py-3 text-sm font-bold">Calculate</Link></div></div></div></main>}
