

ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS cycle_interest_due DOUBLE PRECISION NOT NULL DEFAULT 0.0;

ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS cycle_interest_remaining DOUBLE PRECISION NOT NULL DEFAULT 0.0;

