package com.patrick.fintech.loan_backend.dto;

import com.patrick.fintech.loan_backend.model.Loan;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/** Public API representation of a loan. Never exposes JPA relationships. */
@Data
public class LoanResponse {
    private Long id;
    private String referenceNumber;
    private Long organizationId;
    private Long branchId;
    private Long borrowerId;
    private String borrowerName;
    private Long createdById;
    private Long approvedById;
    private Long loanOfficerId;
    private Loan.LoanType loanType;
    private com.patrick.fintech.loan_backend.model.LoanStatus status;
    private Loan.CreditQuality creditQuality;
    private Loan.ArrearsStatus arrearsStatus;
    private LocalDateTime classifiedAt;
    private Loan.RepaymentFrequency repaymentFrequency;
    private BigDecimal amount;
    private BigDecimal requestedAmount;
    private BigDecimal disbursedAmount;
    private BigDecimal netDisbursedAmount;
    private BigDecimal totalRepayable;
    private BigDecimal totalPaid;
    private BigDecimal principalPaid;
    private BigDecimal outstandingBalance;
    private BigDecimal nextInstallmentAmount;
    private LocalDate nextPaymentDate;
    private LocalDate nextDueDate;
    private LocalDate lastPaymentDate;
    private Integer missedInstallments;
    private Integer daysOverdue;
    private BigDecimal interestRate;
    private String interestRateType;
    private BigDecimal managementFeeRate;
    private BigDecimal managementFee;
    private BigDecimal managementFeePaid;
    private BigDecimal managementFeeOutstanding;
    private BigDecimal totalInterest;
    private BigDecimal interestPaid;
    private BigDecimal interestOutstanding;
    private BigDecimal penaltiesAssessed;
    private BigDecimal penaltiesPaid;
    private Integer durationMonths;
    private String currency;
    private BigDecimal applicationFeeRate;
    private BigDecimal applicationFee;
    private BigDecimal applicationFeePaid;
    private BigDecimal extensionFeeAssessed;
    private BigDecimal extensionFeePaid;
    private BigDecimal extensionFeeOutstanding;
    private Integer extensionCount;
    private LocalDate lastExtensionDate;
    private String notes;
    private String purpose;
    private String collateralDescription;
    private BigDecimal collateralValue;
    private String rejectionReason;
    private Boolean imported;
    private Long importBatchId;
    private BigDecimal riskScore;
    private String riskCategory;
    private BigDecimal debtToIncomeRatio;
    private Integer creditScoreSnapshot;
    private LocalDate startDate;
    private LocalDate approvedAt;
    private LocalDateTime disbursedAt;
    private LocalDate maturityDate;
    private LocalDateTime disbursedAtTimestamp;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime termsAcceptedAt;
}
