package com.patrick.fintech.loan_backend.controller;
import com.patrick.fintech.loan_backend.dto.ApiResponse; import com.patrick.fintech.loan_backend.model.Organization; import com.patrick.fintech.loan_backend.service.BankReconciliationService; import com.patrick.fintech.loan_backend.repository.OrganizationRepository; import com.patrick.fintech.loan_backend.util.CurrentUserUtil; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.time.*;
@RestController @RequestMapping("/api/accounting/bank-reconciliation") @RequiredArgsConstructor @PreAuthorize("hasAnyRole('ADMIN','MANAGER','ACCOUNTANT')") public class BankReconciliationController{
 private final BankReconciliationService service; private final com.patrick.fintech.loan_backend.service.FinancialApprovalService approvalService; private final OrganizationRepository orgRepo; private final CurrentUserUtil current;
 @PostMapping("/{bankAccountId}/import") public ResponseEntity<ApiResponse<Integer>> importCsv(@PathVariable Long bankAccountId,@RequestParam("file")MultipartFile file)throws Exception{Organization o=org();int n=service.importCsv(o,bankAccountId,file.getInputStream(),current.getCurrentUser().getName());return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.safe(n));}
 @PostMapping("/{bankAccountId}/reconcile") public ResponseEntity<ApiResponse<BankReconciliationService.ReconciliationResult>> reconcile(@PathVariable Long bankAccountId,@RequestParam String from,@RequestParam String to){Organization o=org();return ResponseEntity.ok(ApiResponse.safe(service.reconcile(o,bankAccountId,LocalDate.parse(from),LocalDate.parse(to),current.getCurrentUser().getName())));}
 @PostMapping("/{bankAccountId}/sign") public ResponseEntity<ApiResponse<com.patrick.fintech.loan_backend.model.FinancialApproval>> sign(@PathVariable Long bankAccountId,@RequestParam String from,@RequestParam String to,@RequestParam String reportHash,@RequestParam Long approvalId){Organization o=org();var a=approvalService.requireApproved(approvalId,o,"BANK_RECONCILIATION",bankAccountId+"|"+from+"|"+to);if(reportHash==null||reportHash.isBlank()||!reportHash.equalsIgnoreCase(a.getPayloadHash()))throw new IllegalStateException("Reconciliation report hash does not match the approved maker payload");return ResponseEntity.ok(ApiResponse.safe(a));}
 private Organization org(){return orgRepo.findById(current.getCurrentOrganizationId()).orElseThrow(()->new IllegalStateException("Organization not found"));}
}
